version: "3.7"

networks:
  api-v2-mock-network:
    name: api-v2-mock-network

services:

  # Simplified Eliona database as backend for the API-v2 server.
  # The database can be connected with: CONNECTION_STRING=postgres://postgres:postgres@localhost:5432
  database:
    container_name: database-mock
    image: debezium/postgres:12
    environment:
      POSTGRES_PASSWORD: secret
      PGPORT: 5432
      TZ: Europe/Zurich
    networks:
      api-v2-mock-network:
    volumes:
      - ./mock/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    ports:
      - "5432:5432"

  # Server representing the Eliona API v2.
  # The API endpoint can be connected with: API_ENDPOINT=http://localhost:3000}/v2
  api-v2:
    container_name: api-v2
    image: eliona/api-v2:latest
    environment:
      CONNECTION_STRING: postgres://postgres:secret@database-mock:5432
    networks:
      api-v2-mock-network:
    restart: always
    ports:
      - "3000:3000"
  
  bitcoin-app:
    build: .
    container_name: example-bitcoin
    environment:
      APPNAME : "example"
      CONNECTION_STRING : "postgres://postgres:secret@database-mock:5432"
      API_TOKEN : "secret"
      API_ENDPOINT : "http://api-v2:3000/v2"
      API_SERVER_PORT : "3001"
    networks:
      api-v2-mock-network:
    restart: always
    ports:
      - "3001:3001"