/*
 * Bitcoin-app API
 *
 * Minimal API for bitcoin-app configuration
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package apiserver

import (
	"context"
	"net/http"
)



// DefaultApiRouter defines the required methods for binding the api requests to a responses for the DefaultApi
// The DefaultApiRouter implementation should parse necessary information from the http request,
// pass the data to a DefaultApiServicer to perform the required actions, then write the service results to the http response.
type DefaultApiRouter interface { 
	AddCurrencyToProjectPost(http.ResponseWriter, *http.Request)
	ConfigEndpointPost(http.ResponseWriter, *http.Request)
	ConfigGet(http.ResponseWriter, *http.Request)
	ConfigPollRatePost(http.ResponseWriter, *http.Request)
	ConfigTimeoutPost(http.ResponseWriter, *http.Request)
}


// DefaultApiServicer defines the api actions for the DefaultApi service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type DefaultApiServicer interface { 
	AddCurrencyToProjectPost(context.Context, CurrencyUpdate) (ImplResponse, error)
	ConfigEndpointPost(context.Context, ConfigurationFieldUpdate) (ImplResponse, error)
	ConfigGet(context.Context) (ImplResponse, error)
	ConfigPollRatePost(context.Context, ConfigurationFieldUpdate) (ImplResponse, error)
	ConfigTimeoutPost(context.Context, ConfigurationFieldUpdate) (ImplResponse, error)
}
