/*
 * Bitcoin-app API
 *
 * Minimal API for bitcoin-app configuration
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package apiserver

// ConfigurationFieldUpdate - 
type ConfigurationFieldUpdate struct {

	NewValue string `json:"newValue,omitempty"`
}

// AssertConfigurationFieldUpdateRequired checks if the required fields are not zero-ed
func AssertConfigurationFieldUpdateRequired(obj ConfigurationFieldUpdate) error {
	return nil
}

// AssertRecurseConfigurationFieldUpdateRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of ConfigurationFieldUpdate (e.g. [][]ConfigurationFieldUpdate), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseConfigurationFieldUpdateRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aConfigurationFieldUpdate, ok := obj.(ConfigurationFieldUpdate)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertConfigurationFieldUpdateRequired(aConfigurationFieldUpdate)
	})
}
